### ISSUE TITLE
Setting app.run (host) to "localhost" doesn't allow binding from other locations

### ISSUE THREAD

**Issue by joelrader** [pingidentity/pingone-customers-sample-registration#6]
Suggestion: Change "localhost" to "0.0.0.0". That way if you deploy to another location you don't have to modify this value. Shouldn't be a security issue for a sample app.

**Comment by richardcardona** [comment]
Spoken like a true RSA. Since you don't know where the sample will be deployed or whether a security vulnerability will be discovered in a dependency within the project, e.g. Spring Boot, `localhost` is the more secure deployment option. Deployers _should be required_ to actively change the bind address to a specific interface or all interfaces with active knowledge of the application's accessibility.

**Comment by joelrader** [comment]
> Spoken like a true RSA. Since you don't know where the sample will be deployed or whether a security vulnerability will be discovered in a dependency within the project, e.g. Spring Boot, `localhost` is the more secure deployment option. Deployers _should be required_ to actively change the bind address to a specific interface or all interfaces with active knowledge of the application's accessibility.

That's a fair point. For my testing I'm deploying out to an app server that's running Docker containers, so it's easy to modify that value. Only challenge is once you put it someplace other than localhost then it breaks re-directs in P14C, since only HTTPS locations are allowed. Then you have to go down the rabbit hole of setting up (python/flask) with HTTPS.

Thanks!
